/** Symbol ids available in /public/assets/icons/icons.svg (Tabler outline icons). */
export const iconNames = [
  "alert-circle",
  "alert-octagon",
  "alert-triangle",
  "arrow-right",
  "bell-ringing",
  "bolt",
  "broadcast",
  "building-skyscraper",
  "building-store",
  "buildings",
  "calendar-event",
  "chart-bar",
  "check",
  "chef-hat",
  "chevron-down",
  "circle-check",
  "clipboard-list",
  "clock",
  "cpu",
  "database",
  "device-mobile",
  "download",
  "droplet",
  "external-link",
  "file",
  "file-check",
  "headset",
  "info-circle",
  "loader-2",
  "lock",
  "login-2",
  "mail",
  "menu-2",
  "message",
  "moon",
  "phone",
  "player-pause",
  "premium-rights",
  "refresh",
  "robot",
  "scale",
  "send",
  "shield-check",
  "tool",
  "user",
  "wave-saw-tool",
  "wifi",
  "wifi-off",
  "world",
  "x",
  "chevron-right",
] as const;

export type IconName = (typeof iconNames)[number];

export const ICON_SPRITE_URL = "/assets/icons/icons.svg";
